@echo off
echo Starting FastAPI server in background...
start /B uvicorn src.main:app --reload

echo Waiting 3 seconds for server to start...
timeout /t 3 /nobreak > nul

echo Running authentication test...
python test_auth.py

echo Test completed. Press any key to stop the server...
pause > nul

echo Stopping server...
taskkill /f /im python.exe > nul 2>&1
